import streamlit as st
import google.generativeai as genai
import random

genai.configure(api_key="YOUR_API_KEY")

generation_config = {
    "temperature": 0.75,
    "top_p": 0.95,
    "top_k": 64,
    "max_output_tokens": 8192,
}

model = genai.GenerativeModel(
    model_name="models/gemini-flash-lite-latest",
    generation_config=generation_config
)

def get_joke():
    jokes = [
        "Why did the AI chef break up with the recipe? Too many mixed signals in the ingredients.",
        "Why don’t programmers trust recipes generated by AI? They keep saying, ‘Just one more iteration.’",
        "Why did the chef bring a laptop into the kitchen? To run the Flavour Fusion app.",
        "Why did the recipe refuse to compile? Missing ingredients and too many dependencies.",
        "Why does the AI love cooking? Because it can finally use all its processors.",
        "Why was the AI recipe so confident? It had all the right parameters tuned.",
        "Why did the food blogger love Flavour Fusion? Because it generates content faster than preheating an oven.",
        "Why did the cake trust the AI chef? It followed the recipe step by step—no bugs involved."
    ]
    return random.choice(jokes)

def recipe_generation(user_input, word_count):
    try:
        st.info("⏳ Generating your recipe...")
        st.write(
            "😂 While I work on creating your blog, here's a little joke to keep you entertained:\n\n"
            f"**{get_joke()}**"
        )

        prompt = (
            f"Write a detailed recipe blog on the topic '{user_input}' "
            f"with approximately {word_count} words. "
            "Include an introduction, ingredients, step-by-step instructions, tips, and serving suggestions."
        )

        chat_session = model.start_chat(history=[])
        response = chat_session.send_message(prompt)

        st.success("✅ Your recipe is ready!")
        return response.text

    except Exception as e:
        st.error(f"❌ Error generating recipe: {e}")
        return None

st.set_page_config(page_title="Flavour Fusion", page_icon="🍽️", layout="centered")

st.title("🍽️ Flavour Fusion: AI-Driven Recipe Blogging")
st.write("👩‍🍳 Hello! I'm **Flavour Fusion**, your friendly AI chef. Let’s cook up something amazing!")

topic = st.text_input("🍜 Enter Recipe Topic", placeholder="e.g., Vegan Chocolate Cake")
word_count = st.number_input("📝 Number of Words", min_value=300, max_value=2000, step=100)

if st.button("✨ Generate Recipe"):
    if topic.strip() == "":
        st.warning("⚠️ Please enter a recipe topic.")
    else:
        result = recipe_generation(topic, int(word_count))
        if result:
            st.markdown("---")
            st.markdown(result)


